def test_failure():
    raise Exception('oh noes')
